name: diaryapp2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^3.0.6
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  shared_preferences: ^2.1.0
  intl: ^0.20.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
